GET http://localhost:3001/getToken

###
GET http://localhost:3001/token/getGenres
Content-Type: application/json
Authorization: BQCVsAvW4cO0iY5GG1N1I3-CbCCNoCnJlJ4mWNAnnzULbo4yOr-hGLx6kQQ1jhuWcuQQwzI8DgUQgL_aLgk

###
GET http://localhost:3001/token/search
Content-Type: application/json
Authorization: BQCVjcoD32OYhmhzc6InjZYWqbTvol3qbr0zAr63njrSNBNi0IxV8wTO7R01u3qI4_nz1-zGA2-G2y4D75E

{
    "q": "123"
}

###
GET http://localhost:3001/token/recs
Content-Type: application/json
Authorization: BQCVjcoD32OYhmhzc6InjZYWqbTvol3qbr0zAr63njrSNBNi0IxV8wTO7R01u3qI4_nz1-zGA2-G2y4D75E

{
    "seed_genres": "pop"
}

###
GET http://localhost:3001/userToken/getUser
Content-Type: application/json
Authorization: BQBexLWaTr-ImALXs8RO_L71gGK2bqQFB92mbyqGNKshf8Fb54lABp3PZ3ZFAxn-umfqh7SePtEoBd9vwGr9GiFCjgAwEZOqc5YihgXxe7UYxZ1C-hUdBqd-SRrIp1_lu-qnzj39vMIn45hgX0LTeQpG4xqJg-TYFFDEzvD9BZkpuLG1-3n6wzbos9E6_CjTKqDvwfFLnZ8i7OweI1TP77Srdw32DsbMxlaIfKss3Ez1tM6tYzPQ7CGxnrZk

###
POST http://localhost:3001/userToken/makeplaylist
Content-Type: application/json
Authorization: BQBexLWaTr-ImALXs8RO_L71gGK2bqQFB92mbyqGNKshf8Fb54lABp3PZ3ZFAxn-umfqh7SePtEoBd9vwGr9GiFCjgAwEZOqc5YihgXxe7UYxZ1C-hUdBqd-SRrIp1_lu-qnzj39vMIn45hgX0LTeQpG4xqJg-TYFFDEzvD9BZkpuLG1-3n6wzbos9E6_CjTKqDvwfFLnZ8i7OweI1TP77Srdw32DsbMxlaIfKss3Ez1tM6tYzPQ7CGxnrZk

{
    "userid": "24tflyyufr37ylwmavqc28a1m"
}

###
POST http://localhost:3001/userToken/addtoplaylist
Content-Type: application/json
Authorization: BQBexLWaTr-ImALXs8RO_L71gGK2bqQFB92mbyqGNKshf8Fb54lABp3PZ3ZFAxn-umfqh7SePtEoBd9vwGr9GiFCjgAwEZOqc5YihgXxe7UYxZ1C-hUdBqd-SRrIp1_lu-qnzj39vMIn45hgX0LTeQpG4xqJg-TYFFDEzvD9BZkpuLG1-3n6wzbos9E6_CjTKqDvwfFLnZ8i7OweI1TP77Srdw32DsbMxlaIfKss3Ez1tM6tYzPQ7CGxnrZk

{
    "uris": ["spotify:track:47Bg6IrMed1GPbxRgwH2aC"],
    "playlistid": "2A1m7OTgFJlD6M0vzz7ccn"
}